
#
###################################
# Site wide configuration
####################################
#
title: "PhD, Vladimir Korzinov"
email: "korzinovvv@gmail.com"
description: "Personal Website"

owner:
  name: Vladimir Korzinov
  avatar: avatar.png
  job: "Data Scientist"
  bio: "student > engineer > economist > data scientist"
  email: "korzinovvv@gmail.com"
  twitter: "@vvkorz"
  github: "vvkorz"
  bitbucket: protvino
  linkedin: vladimirkorzinov

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag